[package]
name = "google_foobar_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# like itertools in Python 2.7 which is allowed to use by this challenge
itertools = "0.13"
